spring.application.name=api-gateway
server.port=8080

# # --- Task Service Route ---
# spring.cloud.gateway.routes[0].id=task-service
# spring.cloud.gateway.routes[0].uri=http://localhost:8082
# spring.cloud.gateway.routes[0].predicates[0]=Path=/tasks/**

# # --- AI Service Route ---
# spring.cloud.gateway.routes[1].id=ai-service
# spring.cloud.gateway.routes[1].uri=http://localhost:8083
# spring.cloud.gateway.routes[1].predicates[0]=Path=/ai/**

# spring.cloud.gateway.routes[0].uri=lb://task-service

# Import properties from this URI i.e. Configuration Server
spring.config.import=option:configserver:http://localhost:8888