server.port=8080

spring.cloud.gateway.routes[0].id=task-service
spring.cloud.gateway.routes[0].uri=lb://task-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/tasks/**

spring.cloud.gateway.routes[1].id=ai-service
spring.cloud.gateway.routes[1].uri=lb://ai-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/ai/**