server.port=8081

jwt.secret=MyLittleSecret-Which-is-not-very-little-but-actually-very-long-secret
jwt.expiration=3600000

# Docker
# spring.datasource.url=jdbc:mysql://mysql:3306/userDb

spring.datasource.url=jdbc:mysql://localhost:3306/userDb
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

auth.permit-all-paths=/auth/register,/auth/login,/auth/validate