server.port=8082

# Docker
# spring.datasource.url=jdbc:mysql://mysql:3306/taskDb
# Local
spring.datasource.url=jdbc:mysql://localhost:3306/taskDb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.kafka.topic.task-ai=task-ai-request


# server.port=8082
# app.kafka.topic.task-ai=${TASK_AI_TOPIC}

# # Database (MySQL)
# spring.datasource.url=${TASK_DB_URL}
# spring.datasource.username=${TASK_DB_USER}
# spring.datasource.password=${TASK_DB_PASS}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true