spring.application.name=auth-service

# Import properties from this URI i.e. Configuration Server

#Docker
# spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
# Local
spring.config.import=optional:configserver:http://localhost:8888