spring.application.name=discovery-service

server.port=8761

# Don't register itself (This helps Eureka to discover the available services to interact the helps load balancer to redirect traffic to correct service)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Import properties from this URI i.e. Configuration Server
spring.config.import=optional:configserver:${http://config-service:8888:http://localhost:8888}